---
- name: Ensure rtx_data_dir {{ rtx_data_dir }}
  ansible.builtin.file:
    path: "{{ rtx_data_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true
    state: directory
    mode: "0755"
  become_user: root
  become: true

- name: Ensure rtx_binary_installation_dir {{ rtx_binary_installation_dir }}
  ansible.builtin.file:
    path: "{{ rtx_binary_installation_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: "0755"

- name: Print rtx_binary_installation_path
  ansible.builtin.debug:
    var: rtx_binary_installation_path
    verbosity: 3

- name: Install rtx binary to {{ rtx_binary_installation_dir }}
  ansible.builtin.get_url:
    # https://github.com/jdxcode/rtx/releases/download/v1.30.4/rtx-v1.30.4-linux-arm64
    url: "{{ rtx_download_url }}"
    dest: "{{ rtx_binary_installation_path }}"
    mode: "755"

- name: Include rtx system wide task
  ansible.builtin.include_tasks: install-rtx-system-wide.yml
  when: system_wide | bool

- name: Include rtx user wide task
  ansible.builtin.include_tasks: install-rtx-user-wide.yml
  when: not (system_wide | bool)
