---
- name: Ensure RTX_DATA_DIR presence and ownership
  ansible.builtin.file:
    path: "{{ rtx_data_dir }}"
    owner: "{{ ansible_user }}"
    # group: "{{ rtx_group }}"
    state: directory
    mode: "0755"

- name: Source rtx script
  ansible.builtin.template:
    src: rtx.sh.j2
    dest: /etc/profile.d/rtx.sh
    owner: root
    group: root
    mode: "0755"
  become: true