---
# 
# Set rtx_dir
# 
- name: Set rtx_dir to /opt/rtx when system_wide is true
  ansible.builtin.set_fact:
    rtx_dir: /opt/rtx
  when: system_wide is true

- name: Ensure rtx_dir presence and ownership
  ansible.builtin.file:
    path: "{{ rtx_dir }}"
    owner: "{{ rtx_user }}"
    group: "{{ rtx_group }}"
    state: directory
    mode: "0755"

- name: Source rtx script
  ansible.builtin.template:
    src: rtx.sh.j2
    dest: /etc/profile.d/rtx.sh
    owner: root
    group: root
    mode: "0755"
  become: true