---
- name: Remove /etc/profile.d/rtx.sh if exists in user_wide mode
  ansible.builtin.file:
    path: /etc/profile.d/rtx.sh
    state: absent
  become: true

- name: Remove /usr/local/bin/rtx if exists in user_wide mode
  ansible.builtin.file:
    path: /usr/local/bin/rtx
    state: absent
  become: true

# - name: Get user home directory
#   ansible.builtin.shell:
#     executable: "{{ bash_executable_path }}"
#     cmd: |
#       #! /usr/bin/env bash
#       set -o pipefail
#       getent passwd {{ rtx_user }}  | awk -F: '{ print $6 }'
#   changed_when: false
#   register: user_home

# - name: Update bashrc
#   ansible.builtin.lineinfile:
#     dest: "$HOME/.bashrc"
#     create: true
#     mode: "0644"
#     line: export RTX_DATA_DIR=$HOME/.local/share/rtx
#     regexp: ^export RTX_DATA_DIR=$HOME/.local/share/rtx

# - name: Update bashrc
#   ansible.builtin.lineinfile:
#     dest: "$HOME/.bashrc"
#     create: true
#     mode: "0644"
#     line: eval "$(~/bin/rtx activate bash)"
#     regexp: ^eval "$(~/bin/rtx activate bash)"

- name: Update and Source bashrc
  ansible.builtin.shell:
    executable: "{{ bash_executable_path }}"
    cmd: |
      #! /usr/bin/env bash
      set -o pipefail
      LINE='eval "$(~/bin/rtx activate bash)"'
      grep -qF -- "$LINE" "$HOME/.bashrc" || echo "$LINE" >> "$HOME/.bashrc"
      source $HOME/.bashrc
      echo bashrc sourced
  changed_when: false
  become_user: "{{ ansible_user }}"
