---
# tasks file for rtx

# - debug:
#     msg: "{{ item.key }} {{ item.value|json_query('[]') }}"
#   loop: '{{ lookup("dict", rtx_plugins) }}'

- name: Print Gathered facts
  ansible.builtin.debug:
    msg:
      - "ansible_architecture: {{ ansible_architecture }}"
      - "ansible_os_family: {{ ansible_os_family }}"
      - "ansible_distribution: {{ ansible_distribution }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_pkg_mgr: {{ ansible_pkg_mgr }}"

- name: Install rtx
  ansible.builtin.import_tasks: install-rtx.yml

- name: Update package cache
  ansible.builtin.import_tasks: update-package-cache.yml

- name: Install global dependencies
  ansible.builtin.import_tasks: install-plugin-global-dependencies.yml

- name: Install plugin specific dependencies
  ansible.builtin.import_tasks: install-plugin-specific-dependencies.yml

- name: "Extract name into a list and register variable plugins_to_install from vars: rtx_plugins"
  set_fact:
    plugins_to_install: "{{ rtx_plugins | map(attribute='name') | list }}"

# - debug:
#     msg: "{{plugins_to_install}}"

- name: Install plugins and apps
  ansible.builtin.import_tasks: install-plugins-and-apps.yml
