---
- name: Print Gathered facts
  ansible.builtin.debug:
    msg:
      - "ansible_architecture: {{ ansible_architecture }}"
      - "ansible_os_family: {{ ansible_os_family }}"
      - "ansible_distribution: {{ ansible_distribution }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_distribution_version: {{ ansible_distribution_version }}"
      - "ansible_pkg_mgr: {{ ansible_pkg_mgr }}"
      - "ansible_user: {{ ansible_user }}"

- name: Set facts
  ansible.builtin.import_tasks: set-facts.yml

- name: Install rtx
  ansible.builtin.import_tasks: install-rtx.yml

- name: Update package cache
  ansible.builtin.import_tasks: update-package-cache.yml

- name: Install global dependencies
  ansible.builtin.import_tasks: install-plugin-global-dependencies.yml

- name: Install plugin specific dependencies
  ansible.builtin.import_tasks: install-plugin-specific-dependencies.yml

- name: Install plugins and apps
  ansible.builtin.import_tasks: install-plugins-and-apps.yml
