---
- name: Print Gathered facts
  ansible.builtin.debug:
    msg:
      - "ansible_architecture: {{ ansible_architecture }}"
      - "ansible_os_family: {{ ansible_os_family }}"
      - "ansible_distribution: {{ ansible_distribution }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_distribution_version: {{ ansible_distribution_version }}"
      - "ansible_pkg_mgr: {{ ansible_pkg_mgr }}"
      - "ansible_user: {{ ansible_user }}"
  tags:
    - always

# - set_fact:
#     ansible_ssh_user: "{{ lookup('env', 'SSH_USER') | default('deploy', true) }}"
#     http_proxy: "{{ http_proxy | default(omit) }}"
#     https_proxy: "{{ https_proxy | default(omit) }}"
#   tags:
#     - always

# - debug:
#     var: http_proxy
#   tags:
#     - always

# - debug:
#     var: https_proxy
#   tags:
#     - always

- name: Set facts
  ansible.builtin.import_tasks: set-facts.yml
  tags:
    - always

- name: Install rtx
  ansible.builtin.import_tasks: install-rtx.yml
  tags:
    - rtx-binary

- name: Update package cache
  ansible.builtin.import_tasks: update-package-cache.yml
  tags:
    - plugin-dependencies

- name: Install global dependencies
  ansible.builtin.import_tasks: install-plugin-global-dependencies.yml
  tags:
    - plugin-dependencies

- name: Install plugin specific dependencies
  ansible.builtin.import_tasks: install-plugin-specific-dependencies.yml
  tags:
    - plugin-dependencies

- name: Install plugins and apps
  ansible.builtin.import_tasks: install-plugins-and-apps.yml
  tags:
    - rtx-apps
