---
# tasks file for rtx

- name: Install rtx
  ansible.builtin.import_tasks: install.yml
- name: Include os-specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
- name: Install plugins
  ansible.builtin.import_tasks: plugins.yml
