# set facts
- name: Determine Bash executable path
  ansible.builtin.shell:
    cmd: "which bash"
  register: bash_path_result

- name: Set facts
  set_fact:
    bash_executable_path: "{{ bash_path_result.stdout }}"
