---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # - name: Example assertion
    #   ansible.builtin.assert:
    #     that: 
    #       - ansible_host is defined

    # - name: Populate service facts
    #   ansible.builtin.service_facts:

    # - name: Print service facts
    #   ansible.builtin.debug:
    #     var: ansible_facts.services

    - name: Populate rtx version
      ansible.builtin.command: rtx version
      register: rtx_version # <- Registers the command output.
      changed_when: rtx_version.rc != 0 # <- Uses the return code to define when the task has changed.
      # changed_when: false # or just make a task show as unchanged

    - name: Print rtx version
      ansible.builtin.debug:
        var: rtx_version.stdout

    - name: Assert rtx version
      ansible.builtin.assert:
        that: "'1.30.4' in rtx_version.stdout"
